export {default as Header} from './header/Header'
export {default as Hero} from './hero/Hero'
export {default as Logo} from './logo/Logo'
export {default as Whatisgpt} from './whatisgpt/Whatisgpt'
export {default as What} from './what/What'
export {default as Future} from './future/Future'
export {default as Myapps} from './myapps/Myapps'
export {default as Register} from './register/Register'
export {default as Blog} from './blog/Blog'
export {default as Access } from './access/Access'
export{default as Footer} from './footer/Footer'